### AB_ReAP 

## 6TH ANNUAL FORUM-CONFERENCE AND WORKSHOP

##### 13-02-2024

### Lab2: Exercise2

1. Create a list

Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables.

Print areas with the print() function.

In [1]:
# area variables (in square meters)
hall= 11.25
kit= 18.0
liv= 20.0
bed= 10.75
bath= 9.50

# Create list areas
areas= [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


2. Create list with different types

Finish the code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings "hallway", "kitchen" and "bedroom" at the appropriate locations.

Print areas again; is the printout more informative this time?

In [12]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas 
areas= ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


3. Select the valid list

Can you tell which ones of the following lines of Python code are valid ways to build a list?

A. [1, 3, 4, 2] <br>B. [[1, 2, 3], [4, 5, 7]] <br>C. [1 + 2, "a" * 5, 3]

4. List of lists

* Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
* Print out house; does this way of structuring your data make more sense?
* Print out the type of house. Are you still dealing with a list?

In [1]:
# area variables (in square meters)
["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.5]

# house information as list of lists
house= ["hallway", 11.25, "kitchen", 18.0, "living room",
                    20.0, "bedroom", 10.75, "bathroom", 9.5]

# Print out house
print(house)

# Print out the type of house
print(type(house))

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
<class 'list'>


5. Subset and conquer

Print out the second element from the areas list (it has the value 11.25).

Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!

Select the number representing the area of the living room (20.0) and print it out.

In [15]:
# Create the areas list
areas= ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.5]

# Print out second element from areas
print(areas[1:2])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5:6])

[11.25]
9.5
[20.0]


6. Subset and calculate

Using a combination of list subsetting and variable assignment, create a new variable, eat_sleep_area, that contains the sum of the area of the kitchen and the area of the bedroom.

Print the new variable eat_sleep_area.


In [25]:
## Create the areas list
["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.5]


# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area= areas[3:4] + areas[7:8]

# Print the variable eat_sleep_area
print(eat_sleep_area)



[18.0, 10.75]


7. Slicing and dicing

Use slicing to create a list, downstairs, that contains the first 6 elements of areas.

Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas.

Print both downstairs and upstairs using print().

In [15]:
# Create the areas list

["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.5]

# Use slicing to create downstairs
upstairs= areas[0:6]

# Use slicing to create upstairs
downstairs= areas[6:]

# Print out downstairs and upstairs
print(upstairs, downstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0] ['bedroom', 10.75, 'bathroom', 9.5]


8. Slicing and dicing

Use slicing to create a list, downstairs, that contains the first 6 elements of areas.

Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas.

Print both downstairs and upstairs using print().

In [ ]:
# Create the areas list


# Use slicing to create downstairs

# Use slicing to create upstairs


# Print out downstairs and upstairs



9. Slicing and dicing (2)

Create downstairs again, as the first 6 elements of areas. This time, simplify the slicing by omitting the begin index.

Create upstairs again, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.

In [17]:
# Create the areas list
["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.5]

# Alternative slicing to create downstairs
upstairs= areas[1:6]

# Alternative slicing to create upstairs
downstairs= areas[5:]

10. Replace list elements

Update the area of the bathroom area to be 10.50 square meters instead of 9.50.

Make the areas list more trendy! Change "living room" to "chill zone".

In [32]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1]= 10.50
print(areas)


# Change "living room" to "chill zone"
areas[4]= "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


11. Extend a list

Use the + operator to paste the list ["poolhouse", 24.5] to the end of the areas list. Store the resulting list as areas_1.

Further extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2.

In [39]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1= areas + ["poolhouse", 24.5]
print(areas_1)

# Add garage data to areas_1, new list is areas_2
areas_2= areas_1 + ["garage", 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


12. Inner workings of lists

Change the second command, that creates the variable areas_copy, such that areas_copy is an explicit copy of areas. After your edit, changes made to areas_copy shouldn't affect areas. Submit the answer to check this.

In [41]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas[0:4]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


13. Familiar functions

Use print() in combination with type() to print out the type of var1.

Use len() to get the length of the list var1. Wrap it in a print() call to directly print it out.

Use int() to convert var2 to an integer. Store the output as out2.

In [42]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2= int(var2)
print(out2)

<class 'list'>
4
1


14. Multiple arguments

Use + to merge the contents of first and second into a new list: full.

Call sorted() on full and specify the reverse argument to be True. Save the sorted list as full_sorted.

Finish off by printing out full_sorted.

In [46]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full= first + second

# Sort full in descending order: full_sorted
full_sorted= sorted(full, reverse= True) 


# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


15. String Methods

Use the upper() method on place and store the result in place_up. Use the syntax for calling methods that you learned in the previous video.

Print out place and place_up. Did both change?

Print out the number of o's on the variable place by calling count() on place and passing the letter 'o' as an input to the method. We're talking about the variable place, not the word "place"!

In [49]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up= place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


16. List Methods

Use the index() method to get the index of the element in areas that is equal to 20.0. Print out this index.

Call count() on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.

In [50]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


17. List Methods (2)

Use append() twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.

Print out areas

Use the reverse() method to reverse the order of the elements in areas.

Print out areas once more.

In [55]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)


# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


18. Import package

Import the math package. Now you can access the constant pi with math.pi.

Calculate the circumference of the circle and store it in C.

Calculate the area of the circle and store it in A.

In [62]:
# Import the math package
import math 

# Definition of radius
r = 0.43

# Calculate C
C =  2 * r * math.pi
print(C)

# Calculate A
A = math.pi * r ** 2
print(A)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

2.701769682087222
0.5808804816487527
Circumference: 2.701769682087222
Area: 0.5808804816487527


19. Selective import

Perform a selective import from the math package where you only import the radians function.

Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to dist. You can calculate this as r * phi, where r is the radius and phi is the angle in radians. To convert an angle in degrees to an angle in radians, use the radians() function, which you just imported.
Print out dist.

In [65]:
# Import radians function of math package
from math import radians

# Definition of radius
r = 192500

# Travel distance of Moon over 12 degrees. Store in dist.
dist= r * radians(12)

# Print out dist
print(dist)

40317.10572106901


20. Your First NumPy Array

Import the numpy package as np, so that you can refer to numpy with np.

Use np.array() to create a numpy array from baseball. Name this array np_baseball.

Print out the type of np_baseball to check that you got it right.

In [66]:
# Import the numpy package as np
import numpy as np

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball= np.array(baseball)

# Print out type of np_baseball
print(np_baseball)

[180 215 210 210 188 176 209 200]


21.You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

height_in is already available and the numpy package is loaded, so you can start straight away 

@instructions

Create a numpy array from height_in. Name this new array np_height_in.
Print np_height_in.
Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
Print out np_height_m and check if the output makes sense.

In [71]:
import pandas as pd
mlb = pd.read_csv("http://assets.datacamp.com/course/intro_to_python/baseball.csv")
height_in = mlb['Height'].tolist()
import numpy as np

In [73]:
# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in= np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m= np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


22. The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: height_in and weight_lb. height_in is in inches and weight_lb is in pounds.

It's now possible to calculate the BMI of each baseball player. Python code to convert height_in to a numpy array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game! height_in and weight_lb are available as regular lists.

@instructions

Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.
Use np_height_m and np_weight_kg to calculate the BMI of each player. Use the following equation: $$ \mathrm{BMI} = \frac{\mathrm{weight (kg)}}{\mathrm{height (m)}^2}$$ Save the resulting numpy array as bmi.
Print out bmi.

In [74]:
import pandas as pd
mlb = pd.read_csv("http://assets.datacamp.com/course/intro_to_python/baseball.csv")
height_in = mlb['Height'].tolist()
weight_lb = mlb['Weight'].tolist()
import numpy as np

In [75]:
# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg= np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi= np_weight_kg / np_height_m **2

# Print out bmi
print(bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


To subset both regular Python lists and numpy arrays, you can use square brackets:

In [ ]:
x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]

For numpy specifically, you can also use boolean numpy arrays:

In [ ]:
high = y > 5
y[high]

23. The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data! height_in and weight_lb are available as regular lists.


Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.
Print the array light.
Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array.

In [76]:
import pandas as pd
mlb = pd.read_csv("http://assets.datacamp.com/course/intro_to_python/baseball.csv")
height_in = mlb['Height'].tolist()
weight_lb = mlb['Weight'].tolist()
import numpy as np

In [78]:
# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light= bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]
